### ISSUE TITLE
InControl mode doesn't start

### ISSUE THREAD

**Issue by ale-saglia** [mvoidex/Launchkey-Mini-MK2-for-Bitwig#1]
Hi, I got a problem using the script, when I plug the keyboard Bitwig successfully recognize the device but the InControl mode doesn't start, so I can just use it as standard midi keyboard.
If I add a controller (like the Launchkey49) in Bitwig and route the midi I/O the InControl mode works and even if I deactivate the device (or restart Bitwig) the InControl keep running and the script work absolutely fine.

**Comment by mvoidex** [comment]
This is known bug, but I have no idea, what am i doing wrong. This issue exists even for empty script (except registering device, of course, which was copy-pasted from provided scripts).
It also sometimes doesn't exit from InControl mode on Bitwig exit, while script should normally send midi message to device.

I'll try to look closer to find out what's wrong.

**Comment by mikobuntu** [comment]
I think I have found the problem with InControl not working, you need to change the line #35 in launchkey.vars.js to 0x0C   ( control change 12 )  //found from looking at a Renoise script//  [ tested and working great here ]

**Comment by ale-saglia** [comment]
I tried @mikobuntu fix and also from here seems to work just fine.

**Comment by mvoidex** [comment]
@mikobuntu, thanks :)
